### PR TITLE
Update demo application to Swift 3

### PR DESCRIPTION
**Pull request by lucascaton**
Even though the demo app was already updated to Swift 3, there are still some changes required. If you open the demo app from `master` branch in Xcode, you'll see several warnings/errors. This PR fixes those.

### CODE REVIEW

**Comment by lucascaton** [comment]
Anyone, please? 😄

**Comment by lucascaton** [comment]
cc: @sstephenson

**Comment by lucascaton** [comment]
Hi @sstephenson, @packagethief, @zachwaugh.
Is anyone maintaining this repo? Thank you.

**Comment by thetizzo** [comment]
@lucascaton it looks like the demo app was already updated to Swift 3 in [this PR](https://github.com/turbolinks/turbolinks-ios/pull/82) which was merged in March.

This PR can probably be closed.

**Comment by lucascaton** [comment]
Hi @thetizzo, not really. As you can see in this PR, there are some changes that are still required.

If you open the demo app from `master` branch in Xcode, you'll see several warnings/errors :)

**Comment by thetizzo** [comment]
Ah, I see two warnings, for the lines you changed in `Session.swift` and `WebView.swift` 😄

**Comment by wassimk** [comment]
I see the same warnings. Thanks for updating @lucascaton. Hopefully it can get a merge.

**Comment by hugoh1995** [comment]
Is this project still alive? This pull request should be merged.

**Comment by fordfischer** [comment]
Project is definitely still alive @dhh just wrote about the benefits of it here: https://m.signalvnoise.com/hybrid-development-is-how-we-give-our-teams-of-three-superpowers-2021a84437d

**Comment by zachwaugh** [comment]
Sorry for the delay! We are definitely still maintaining this framework and rely on it for Basecamp 3. Thanks @lucascaton, just merged!

**Pull request merged**
